#Doctrine extentions
stof_doctrine_extensions:
    default_locale: "%locale%"
    translation_fallback: true
    orm:
        default:
          sluggable: true
          timestampable: true
          sortable: true

#Fos User Bundle
fos_user:
    db_driver: orm
    firewall_name: admin
    user_class: Ai\AdminBundle\Entity\BeUser
    group:
        group_class: Ai\AdminBundle\Entity\BeGroup

#Sonata
sonata_admin:
    title: "%dashboard_title%"
    options:
        html5_validate: true
        confirm_exit: true
        use_select2: true
        use_icheck: true
    templates:
        layout: AiAdminBundle:Admin:standard_layout.html.twig
    dashboard:
        groups:
            ai_admins:
                label: Администрирование:
                icon: <i class="fa fa-cog"></i>
                items:
                    - ai_admin.be_user
                    - ai_admin.be_group
                roles: [ROLE_SUPER_ADMIN]
        blocks:
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [ai_admins]

sonata_block:
    default_contexts: [sonata_page_bundle]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts: [admin]

sonata_doctrine_orm_admin:
    entity_manager: ~
    templates:
        form:
            - AiAdminBundle:Admin:form_admin_fields.html.twig

sonata_cache:
    caches:
#        esi:
#            token: an unique security key # a random one is generated by default
#            servers:
#                - varnishadm -T 127.0.0.1:2000 {{ COMMAND }} "{{ EXPRESSION }}"
#        ssi:
#            token: an unique security key # a random one is generated by default
#        mongo:
#            database:   cache
#            collection: cache
#            servers:
#                - {host: 127.0.0.1, port: 27017, user: username, password: pASS'}
#                - {host: 127.0.0.2}
        memcached:
            prefix: test     # prefix to ensure there is no clash between instances
            servers:
                - {host: 127.0.0.1, port: 11211, weight: 0}
        predis:
            servers:
                - {host: 127.0.0.1, port: 6379, database: 42}
        apc:
            token:  s3cur3   # token used to clear the related cache
            prefix: test     # prefix to ensure there is no clash between instances
            servers:
                - { domain: "%domain%", ip: 127.0.0.1, port: 80}
        symfony:
            token: s3cur3 # token used to clear the related cache
            php_cache_enabled: true # Optional (default: false), clear APC or PHP OPcache
            types: [mytype1, mycustomtype2] # Optional, you can restrict allowed cache types
            servers:
                - { domain: "%domain%", ip: 127.0.0.1, port: 80}

pix_sortable_behavior:
    db_driver: orm

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        admin_thumb:
            quality: 100
            filters:
                thumbnail: { size: [120, 100], mode: outbound }
        be_user_avatar:
            quality: 100
            filters:
                thumbnail: { size: [250, 200], mode: outbound }

#File Uploader
oneup_uploader:
    orphanage:
        maxage: 86400
        directory: "%kernel.cache_dir%/uploader/orphanage"
    mappings:
        be_user_avatar:
            frontend: fineuploader
            use_orphanage: true
            route_prefix: admin
            enable_cancelation: true