_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

_oneup_uploader:
    resource: .
    type: uploader

ai_admin:
    resource: "@AiAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
